name: Pixel Boxed
markdown: redcarpet
pygments: true
exclude: ['Vagrantfile', 'Vagrantprov', 'LICENSE', 'README.md', 'Gruntfile.js', 'package.json', 'node_modules', 'scss']
destination: 'public'
permalink: none